name: Run Google Search Console

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install google-api-python-client google-auth google-auth-oauthlib requests

    - name: Restore credentials files
      run: |
        echo "${{ secrets.CLIENT_SECRET_JSON }}" > client_secret.json
        echo "${{ secrets.TOKEN_JSON }}" > token.json

    - name: Run script
      run: python bulk.py

    - name: Upload report
      uses: actions/upload-artifact@v3
      with:
        name: gsc-report
        path: tokens_report.csv
